# MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# MySQL R2DBC
spring.r2dbc.url=${SPRING_R2DBC_URL}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD}

# Log level
logging.level.root=INFO
logging.level.org.springframework=INFO
