# Puerto del servidor para Docker
server.port=8081


# --- Configuración MySQL (R2DBC) ---
spring.r2dbc.url=r2dbc:mysql://mysql_blackjack:3306/blackjack
spring.r2dbc.username=root
spring.r2dbc.password=root123

# --- Configuración MongoDB (reactivo) ---
spring.data.mongodb.uri=mongodb://mongo_blackjack:27017/blackjack

# --- Configuración Actuator (para comprobar estado) ---
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# --- Nivel de logs ---
logging.level.org.springframework.r2dbc=DEBUG
logging.level.org.springframework.data.mongodb.core=DEBUG
